
services:
  jupyter-notebook:
    build:
      context: ../source   #salgo
      dockerfile: ../pokedex/Dockerfile #entro
    ports:
      - "8888:8888"  
    volumes:
      - .:/home/jovyan/samuel
    container_name: jupyter-notebook

  postgresql:
    image: postgres
    container_name: postgresql_container
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

volumes:
  data:


#docker compose -f ruta_custom-compose.yaml up --build -d