
services:
  jupyter-notebook:
    build:
      context: .
      dockerfile: Dockerfile #Que busque la imagen en la carpeta actual para que lea el Dockerfile
    ports:
      - "8888:8888"  
    volumes:
      - ../workspace:/home/jovyan/work
    container_name: jupyter-notebook